language: node_js
node_js:
  - node
sudo: false
script:
  - npm test
  - travis encrypt $(heroku auth:token) --add deploy.api_key --org
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: devopslab-pipeline
  edge: true
