language: node_js
node_js:
  - node
sudo: false
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: Twsmsr0wec18GqScBL/aIVVOpG5w2pV6itWiHKbg5HnHOo5LwE4/V2sBCj/iSDUB3MZ04BcZW+xX88ElcVWxxd9OY4iDPhyxJHoaz/xCqdrfUgbZzeleB5XMwVw6RdtEkbLjTfa+bcJ1lpvcdjzmAPSH/ydEGl1gkz1nyT+jM/RIL5jHjz8sMA+Eyq/F1vV4seTyis1/dbJfHvKN/wI5aKpmTe29B1Tyscg+GF6TmDOfF0JH6+gJKYGFPLLU60T2j530CURoYrcvI7t+S4ll/jcYaqVswmnLOri/tjM9facptCKbrGLAgZrrhaZw7i+EgA9JdarsyKsKnoKsa0LQQy4W1BwPUbdgSiM5rZduabH4rlZXKEW6PcZ9lMwN2whRWBGx6HKUFA29sPSCkftFAIybWMDpYPSjmVcqC/3j2bX+/O5sbxLg2GwVpD4vX1E8PWEjiTT76NYKbyld9UVcy+M2uPL/OImcDs8HqWQ8T2JUS4seEv7MS93hQEmd5xBOjq68ANuC5fLW5o4hPoicRChA5Pa2eJle6JPHYXPiZ91VRAw7CNa2t1obVFacyAuE3RytbxMuLGNn+bZDx6Xzv6i0f29VG1ciQJCeEcjiXWSRCOstp9bzV85bP2vceaY4Zo3QZkMv+8+yBFdcwd61lXQgtN8oLGo2Qv2FDfVwfIE=
  app: devopslab-pipeline
  edge: true
