language: node_js
node_js:
  - node
sudo: false
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: FFE0sBfYVBZOLUOB1MzLuLML0cGfTwgbr17rS+71wRLjhqFYCsoo8tyuYDjmpeZIJ+acY4sWfLKJUbIMyNW8X2zXcyLotYt49xlV9AY+FW1hPT1biOn19uo15qFW+Ue9+/FBpdH5OrT1V+Jjc+1a5g9+tbLE+iTSqdgf3GpzyygY/Ms/9IHOjLSO0CHxeT4PKuaYaEmNxoXOQJmMtZAwc50QR9RjBaCZLW6d6Q3j+G+c4glVWZlbJ/R7v8NXVWR8Lk4mZ7JhkU6+VuakLMf108vLtajWClIA3tNyHjP4/PzD5U51qYP5qy6mFGbXNPA99jic9XPem/QEMzzyY8nqgjbY2Z2+SoUTF8asIJx1WLs1U3m+WGb9NurUAq9Tf2zCQUO6mEbyfbbjTKl0Z6nhvLIZsvT9nkIwPpryq8E3eW2BtyASiXyR69ZtOahXYawAuj39bBmpqOTkTfpjSinB08PAAJzIMsV5OgbvtEIllafWLoAJKnGPoD/UHmtGimW08bx5fhkLIsDlgKUcs4dAtcKb1cwX1q117PwDrY/vMq/RwuXSjNjdI830dDk3CbKSZvDrOA+cPN2LTJvfE2cOm9QTArkuEPP80iOLJL0c2VlF1AkAeE5/VmKLiDERn6rZ01na12TAcbSRBl4RE52V8mmeGenunbQXcXh6NrI2v20=
  app: devopslab-pipeline
  edge: true
