language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: jkWmIpOF5AytRggPy8D86tzSDJ+z/RztD3U9vstn2z/e2r71X8bKlzyJVx5N0IHYroDpj70Njl4nRwIfjqmMI7tt6CXHpozfDaAmx2D4R7/onw4ilZodL8WcriXHIC7AhY8T5L4P7Ds2g1BGXV7FmtJ7w9u1JDrEmEkA1ddjYPXV2jWbrBnbeELKZdjxaSTrJcJqEUsTLA1cIYYnCcVIQP8TjuEaM9Vn/3Tl65ZLCRm7Rw7EDFvLrSMy4OZNOfFp4VWaq6/jM5CjjtC0xIib2nKDvRrhjBRkHQHzzLTIwcdhvadNmnrCXrUDmLxxAvXY2IOCwwYq6zrOBuis3tyLfQxoaV4zielbLyQK4oAWjBj7OjdU2b0pj2nruduGhC8YxmvtAISaiLkEtOE+UIUerfYyL/JFJ8q6SgUFXc/RI6zK9Az3kiXya9TP+Ik5TkwN7PtF3zz4y7JPuh/6m21Gupqtd27B+1iudnhXqu+6kzC0AjLfQfhp+okN8vuBq+uT5tDTcJ2NlWVU732/YX/I3i/zDdazoUTU+RtzJ+T7Du4+Isx0v3PW9ALO97QX106sRuPTokqwJSTTea7AUUQulNERh9zuEOWoGfxmaYdi7nZTUr+zj104qdM7zMmaGJnmw9zZaVdQyvWbylq6ob4hSDv2QRLUdlhWrow3ORCsA0U=
  app: devopslab-pipeline
  edge: true
