language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: TUdquOkXHSJE4umBUWP35QuD0WE/6tqk/N5mITyQskgfyj+0cUXSK3CX5r/lWYPM5UGIeGd1h2VJi3lrN4GbV+BOCsorPowJHFwutKWsrxz/V8HhsOMhb1h1GDs2+C7zFAGmOKMtUV3AR12ffpS7pE26vkdKKTE1OufcOoLQiWU1eyTz2uAVg5Up/xemubDZgbDalCdijpWGPnBGgWLv0vcck+9HnDeZEhyWBia/8eF+NObAZeUQixuNXUcHccVgW7b5WY6cFN7Lb5rd6b/yI+2ukKH2eYZhMCXBeJSJyu8PnxqUq3+YM67RHwR3TCudpMoAQQ6Vz5lGbv+nDtePLHtdRvqyueFxYDQi4sfMrzjCokzKmqzPNS3AxhY3zVDI9P50DPOyb0+RJW9YX8MMi+xR3a94JZ01mCuY/fbOXTgH8UJ/sKzFXo90Sy5daq1sQx3fqFfIpD4UJ3A2N9Zwwn92MAZydpT6baedQOyYAPgM8MX4Eg64nwFMPn9TZMOfFC2fnfWUCKVH+6PUMpH6pjiXyYcohXRgMPv+8pG7MAjCY7vIRlqaJEw6hYavsEue6STJI/AwgxUpWQk0KHe/GUIKgVbod4n0uC/+hIDoWEKCwcyD8VxeG7jJNs/WkHzIOYzqzUFkn/CcqmFIJd/UOfToByqkCNDgsg2/2UTzDaA=
  app: devopslab-pipeline
  edge: true
